#define cap 0
#define lit int
#define bussin 1
#define no !
#define sus ?
#define fr ;
#define legit void
#define finna {
#define be ==
#define boutta while
#define bruh ,
#define deadass return
#define yikes break
#define ongod (
#define clean char
#define yeet [
#define mf *
#define tryna if
#define tho }
#define respectfully do
#define like ||
#define lackin -
#define poppin for
#define drip :
#define rn ]
#define chill continue
#define af )
#define lowkey <
#define sheeeesh printf
#define lookin =
#define downbad --
#define playin ++
#define wack /
#define dub +
#define highkey >